# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavelanguage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
