# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavelanguage', '0003_diagram_discussion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
