# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavelanguage', '0004_auto_20160414_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='symbol',
            name='proposed',
            field=models.BooleanField(default=False),
        ),
    ]
