# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import djax.content


class Migration(migrations.Migration):

    dependencies = [
        ('cavelanguage', '0005_auto_20160420_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('pic', models.URLField(null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
            bases=(models.Model, djax.content.ACEContent),
        ),
    ]
