# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavelanguage', '0007_auto_20160420_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
